#!/usr/bin/env python3

import signal
import subprocess
import json
import os
import sys
import time
import typing
import hashlib

package_lock_hash_filename = 'node_modules/package_lock_hash'

def main():
  cur_package_lock_hash = hashlib.sha256(open('package-lock.json').read().encode()).hexdigest()

  if (not os.path.exists(package_lock_hash_filename)) or open(package_lock_hash_filename).read().strip() != cur_package_lock_hash:
    # need reinstall
    subprocess.run(['npm', 'install'])
    open(package_lock_hash_filename, 'w').write(cur_package_lock_hash)

if __name__ == '__main__':
  main()
