#!/usr/bin/env python3

import json
import os
import os.path
import argparse
import subprocess
import random
import string
import textwrap
from sys import argv
import http.client
import time

PROJECT_NAME = 'dapp-framework'
DEFAULT_PORT = 8000
NEXT_ENABLED = True
EXPRESS_ENABLED = True
MONGO_ENABLED = True
REDIS_ENABLED = True
WORKER_ENABLED = True # changing this to False will break the CLI (bash & node) functionality, since it uses the worker image
CERTBOT_EMAIL = 'certbot-notifications@tk.co'

DOCKER_INSTALL_SCRIPT = '''
  if ! which dockerd; then
    curl -fsSL https://get.docker.com | bash
  fi
  if ! docker compose >/dev/null 2>&1 && ! which docker-compose; then
    curl -L "https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  fi
'''

config_is_runtime: bool
config_filename: str

def main():
  global args, config, config_is_runtime, config_filename

  proj_dir = os.path.abspath(os.path.dirname(os.path.abspath(__file__)))

  parser = argparse.ArgumentParser(description='run or deploy the application')

  parser.add_argument('config', type=str,
                      help='config filename')
  parser.add_argument('command', type=str, nargs='?',
                      help='command to run -- can be: run, bg, stop, deploy, cli')
  parser.add_argument('command_args', nargs=argparse.REMAINDER)

  args = parser.parse_args()

  config_filename = os.path.abspath(args.config)

  deployment_state_filename: str
  runtime_filename: str

  if config_filename.endswith('.runtime.json'):
    config_is_runtime = True
    runtime_filename = config_filename
    deployment_state_filename = '/dev/null'
  else:
    config_is_runtime = False
    if not config_filename.endswith('.conf.json'):
      raise Exception('config filename must end with .conf.json')
    config_filename_base: str = config_filename[:-len('.conf.json')]
    runtime_filename = config_filename_base + '.runtime.json'
    deployment_state_filename = config_filename_base + '.deployment.json'

  os.environ['deployment_state_filename'] = deployment_state_filename
  os.environ['runtime_filename'] = runtime_filename

  with open(config_filename) as config_f:
    config = json.load(config_f)

  os.chdir(proj_dir)

  if not os.path.exists('.cache'):
    os.mkdir('.cache')

  parse_config()

  if not os.path.exists(deployment_state_filename):
    open(deployment_state_filename, 'w').write('{}')

  # this could be handled dynamically in getConfig, but cleaner to just handle it here.
  # main issue w/ handling in getConfig is that next hot reload may not reload when
  # /opt/deployment.json is changed, so there's no point
  if not config_is_runtime:
    deployment = json.loads(open(deployment_state_filename).read())
    config['public']['contract_deployments'] = deployment.get('contract_deployments', dict())

  print(f'docker-compose command: {compose_command}')

  with open(runtime_filename, 'w') as f:
    json.dump(config, f)

  config_nginx()

  if command in ['fg', 'run']:
    docker_prep()
    docker_compose_call(['up', '--remove-orphans'])
  elif command == 'bg':
    bg()
  elif command == 'stop':
    docker_down()
  elif command == 'clear-data':
    docker_clear_data()
  elif command == 'logs':
    docker_compose_call(['logs', '-f'])
  elif command == 'bash':
    docker_prep_if_down()
    docker_compose_call(['run', 'node', 'bash', '-c', 'bash'])
  elif command == 'node':
    docker_prep_if_down()
    docker_compose_call(['run', 'node', 'bash', '-c', 'node'])
  elif command == 'deploy-contracts':
    docker_prep_if_down()
    docker_compose_call(['run', '--no-deps', 'node', 'misc/deploy-contracts'])
  elif command == 'test-host':
    do_test(where='host')
  elif command == 'test':
    do_test(where='docker')
  elif command == 'compose-call':
    docker_compose_call(args.command_args)
  elif command == 'install-docker':
    run(['bash', '-c', DOCKER_INSTALL_SCRIPT])
  elif command == 'install':
    service_config = textwrap.dedent(f'''
      [Service]
      User=root
      WorkingDirectory={proj_dir}
      ExecStart={proj_dir}/run deployed.runtime.json fg
      ExecStop={proj_dir}/run deployed.runtime.json stop
      Restart=on-failure
      RestartSec=5

      [Unit]
      Description={PROJECT_NAME}
      Requires=docker.service
      After=docker.service
      StartLimitIntervalSec=300
      StartLimitBurst=10

      [Install]
      WantedBy=multi-user.target
    ''')
    with open(f'/etc/systemd/system/{PROJECT_NAME}.service', 'w') as f:
      f.write(service_config)

    run([
      'bash', '-c',
      textwrap.dedent(f'''
        systemctl daemon-reload
        systemctl restart {PROJECT_NAME}
        systemctl enable {PROJECT_NAME}
      ''')
    ])
  elif command == 'logs-remote':
    run([
      'ssh',
      f'root@{host}',
      f'''
        /opt/{PROJECT_NAME}/run /opt/{PROJECT_NAME}/deployed.runtime.json logs
      ''',
    ])
  elif command in ['deploy', 'fg-remote']:
    if not host:
      raise Exception('host must be specified for deploy')

    deployed_config = config.copy()
    if 'deployer' in deployed_config:
      # remove sensitive data like ssh private key, deployment wallet private key
      del deployed_config['deployer']
    open('.cache/deployed.runtime.json', 'w').write(json.dumps(deployed_config))

    if config['deployer'].get('ssh_private_key'):
      keypath = os.path.join('.cache', 'ssh_private_key')
      with open(keypath, 'w') as f:
        f.write(config['deployer']['ssh_private_key'] + '\n')
      os.chmod(keypath, 0o600)
      use_ssh_key_file = True
    else:
      use_ssh_key_file = False

    run([
      'ssh',
    ] + (['-i', '.cache/ssh_private_key'] if use_ssh_key_file else []) + [
      f'root@{host}',
      f'''
        systemctl stop {PROJECT_NAME} || true
        /opt/{PROJECT_NAME}/run /opt/{PROJECT_NAME}/deployed.runtime.json stop || true
      ''',
    ])

    run([
      'rsync',
    ] + (['-e', 'ssh -i .cache/ssh_private_key'] if use_ssh_key_file else []) + [
      '-av',
      '--delete-after',
      '--exclude',
      '.git',
      '--include',
      '/package.json',
      '--include',
      '/package-lock.json',
      '--exclude',
      '/*.conf.json',
      '--exclude',
      '/*.deployment.json',
      '--exclude',
      '/*.runtime.json',
      '--exclude',
      '/*.ipynb',
      '--exclude',
      'node_modules',
      '--exclude',
      'build',
      '--exclude',
      '.cache',
      '--exclude',
      '.vscode',
      '--exclude',
      '.next',
      '--exclude',
      'hardhat',
      './',
      f'root@{host}:/opt/{PROJECT_NAME}/',
    ])

    run([
      'rsync',
    ] + (['-e', 'ssh -i .cache/ssh_private_key'] if use_ssh_key_file else []) + [
      '-av',
      '.cache/deployed.runtime.json',
      f'root@{host}:/opt/{PROJECT_NAME}/',
    ])

    if command == 'fg-remote':
      cmd = 'fg'
    else:
      cmd = 'install'

    run([
      'ssh',
    ] + (['-i', '.cache/ssh_private_key'] if use_ssh_key_file else []) + [
      f'root@{host}',
      f'''
        {DOCKER_INSTALL_SCRIPT}
        /opt/{PROJECT_NAME}/run /opt/{PROJECT_NAME}/deployed.runtime.json {cmd}
      ''',
    ])
  else:
    raise Exception(f'unknown command: {command}')

def do_test(where):
  out = docker_compose_call(['ps'], get_output=True).stdout
  if 'nginx' in out and 'Up' in out:
    already_running = True
  else:
    already_running = False

  if not already_running:
    bg()

  def check_running():
    try:
      conn = http.client.HTTPConnection('localhost:8000')
      conn.request("GET", '/_alive')
      if conn.getresponse().status == 200:
        return True
      else:
        return False
    except Exception:
      return False

  if not check_running():
    print('application not yet running, waiting for it to start...')
    running_check_start_time = time.time()
    while True:
      time.sleep(0.25)
      if check_running():
        print('application is now running! launching test')
        break
      if time.time() - running_check_start_time > 120:
        raise Exception('application took too long to start')

  try:
    if where == 'docker':
      run(compose_command_base + ['-f', compose_file_path('test'), 'build'])
      run(compose_command_base + ['-f', compose_file_path('test'), 'run', 'test'])
    elif where == 'host':
      run(['bash', '-c', 'cd test && npm install && npm test'])
    else:
      raise Exception('invalid `where`')

  finally:
    if not already_running:
      docker_down()

def bg():
  docker_prep()
  docker_compose_call(['up', '-d', '--remove-orphans'])

def run(cmd, get_output=False, ignore_error=False):
  return subprocess.run(cmd, check=not ignore_error, capture_output=get_output, text=get_output)

def docker_compose_call(args, get_output=False, ignore_error=False):
  cmd = compose_command + args
  print(f'docker_compose_call: {cmd}')
  return run(cmd, get_output=get_output, ignore_error=ignore_error)

def docker_down():
  docker_compose_call(['down', '--remove-orphans'], ignore_error=True)

def docker_clear_data():
  docker_compose_call(['down', '--remove-orphans', '--volumes'])

def docker_build():
  docker_compose_call(['build'])

def docker_prep():
  docker_down()
  docker_build()
  npm_install_if_needed()

def npm_install_if_needed():
  docker_compose_call(['run', 'node', 'python3', 'misc/npm-install-if-needed'])

def docker_prep_if_down():
  if not docker_is_up():
    docker_prep()

def docker_is_up():
  try:
    return len(docker_compose_call(['top'], get_output=True).stdout.strip()) > 0
  except:
    docker_compose_call(['top'])
    raise

if subprocess.run(['docker', 'compose'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0:
  compose_command_base = ['docker', 'compose']
else:
  compose_command_base = ['docker-compose']

compose_command_base += ['-p', PROJECT_NAME]

compose_command = compose_command_base.copy()

def compose_file_path(filename):
  return os.path.join('docker-compose', f'{filename}.yml')

def add_compose_config(filename):
  compose_command.append('-f')
  compose_command.append(compose_file_path(filename))

def parse_config():
  global use_ssl, local, port, develop, admin_password, domain, compose_command, mongo_express_enabled, jupyter_enabled, code_server_enabled, host, command

  command = args.command

  add_compose_config('main')

  add_compose_config('node')

  if MONGO_ENABLED:
    add_compose_config('mongo')

  if REDIS_ENABLED:
    add_compose_config('redis')

    if config['server'].get('mongo_exposed_localhost', False):
      add_compose_config('mongo-exposed-localhost')

  mongo_express_enabled = config['server'].get('mongo_express_enabled', False)
  if mongo_express_enabled:
    add_compose_config('mongo-express')

  jupyter_enabled = config['server'].get('jupyter_enabled', False)
  if jupyter_enabled:
    add_compose_config('jupyter')

  code_server_enabled = config['server'].get('code_server_enabled', False)
  if code_server_enabled:
    add_compose_config('code-server')

  if not config_is_runtime:
    host = config['deployer'].get('host')
    domain = config['server'].get('domain')
    if host and not domain:
      domain = host
      config['server']['domain'] = host
  domain = config['server'].get('domain')
  if domain:
    use_ssl = True
    config['public']['base_url'] = f'https://{domain}'
    add_compose_config('with-ssl')
  else:
    use_ssl = False
    config['public']['base_url'] = f'http://localhost:8000'
    add_compose_config('without-ssl')
    # 8/5/22 -- next two lines unused? commenting out for now
    # local = config.get('local', True)
    # port = config.get('port', DEFAULT_PORT)
  admin_password = config['server'].get('admin_password')
  if admin_password is None:
    admin_password = random_password()
    print(f'admin_password - randomly generated for this build: {admin_password}')
  assert admin_password

def random_password():
  rand = random.SystemRandom()
  chars = string.ascii_lowercase + string.ascii_uppercase + string.digits
  return ''.join(random.choice(chars) for _ in range(32))

def config_nginx():
  app_part = textwrap.dedent(f'''
    client_max_body_size 100M;
    gzip on;
    gzip_vary on;
    gzip_min_length 10240;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/x-javascript application/xml;
    proxy_connect_timeout       300;
    proxy_send_timeout          300;
    proxy_read_timeout          300;
    send_timeout                300;
  ''')

  if EXPRESS_ENABLED:
    app_part += textwrap.dedent(f'''
      location /express/ {{
        proxy_pass http://node:8002/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_redirect off;
      }}
    ''')

  if NEXT_ENABLED:
    app_part += textwrap.dedent(f'''
      location / {{
        proxy_pass http://node:8001/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_redirect off;
      }}
    ''')

  if code_server_enabled:
    app_part += textwrap.dedent(f'''
      location /code/ {{
        proxy_pass http://code-server:8080/;

        auth_basic "";
        auth_basic_user_file /opt/htpasswd-admin;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_redirect off;
      }}

      location /stable-30d9c6cd9483b2cc586687151bcbcd635f373630/ {{
        proxy_pass http://code-server:8080/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/;

        auth_basic "";
        auth_basic_user_file /opt/htpasswd-admin;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_redirect off;
      }}

      location /vs/ {{
        proxy_pass http://code-server:8080/vs/;

        auth_basic "";
        auth_basic_user_file /opt/htpasswd-admin;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_redirect off;
      }}
    ''')

  if mongo_express_enabled:
    app_part += textwrap.dedent(f'''
      location /mongo-express/ {{
        proxy_pass http://mongo-express:8081/mongo-express/;

        auth_basic "";
        auth_basic_user_file /opt/htpasswd-admin;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_redirect off;
      }}
    ''')

  if jupyter_enabled:
    app_part += textwrap.dedent(f'''
      location /jupyter/ {{
        proxy_pass http://jupyter:8003/jupyter/;

        auth_basic "";
        auth_basic_user_file /opt/htpasswd-admin;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_redirect off;
      }}
    ''')

  if use_ssl:
    nginx_config = textwrap.dedent(f'''
      server {{
        server_name {domain};

        listen 80;

        return 301 https://{domain}$request_uri;
      }}

      server {{
        server_name {domain};

        listen 443 ssl http2;

        {app_part}

        ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
      }}
    ''')
  else:
    nginx_config = textwrap.dedent(f'''
      server {{
        server_name app;

        listen 8000;

        {app_part}
      }}
    ''')

  with open(os.path.join('.cache', 'nginx-app.conf'), 'w') as f:
    f.write(nginx_config)

  nginx_env = textwrap.dedent(f'''
    USE_SSL={'true' if use_ssl else 'false'}
    CERTBOT_DOMAIN={domain}
    CERTBOT_EMAIL={CERTBOT_EMAIL}
  ''')
  with open(os.path.join('.cache', 'nginx.env'), 'w') as f:
    f.write(nginx_env)

  with open(os.path.join('.cache', 'nginx-admin-password.txt'), 'w') as f:
    f.write(admin_password)

if __name__ == '__main__':
  main()
